# Generated by Django 4.0.3 on 2022-04-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
